version: '3.8'
services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: steam-investment
    volumes:
      - ./sql/create_items_db.sql:/docker-entrypoint-initdb.d/1.sql
      - ./sql/create_item_history_db.sql:/docker-entrypoint-initdb.d/2.sql

  react-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  spring-boot-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/steam-investment
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3